### ISSUE TITLE
Add individual field display param to SzSearchComponent 

### ISSUE THREAD

**Issue by arawinters** [Senzing/sdk-components-ng#15]
There needs to be a way to disable individual fields in the search box. ie 
```html
<sz-search nameHidden="true" identifierHidden="true"></sz-search>
```
or via css vars:
```scss
body {
    --sz-seach-input-name-display: none;
    --sz-seach-input-identifier-display: none;
}
```

this functionality might also be nice for the other components as well.
